In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv(r'C:\Users\user\OneDrive\Desktop\Data Science\Medical-Disease-Predicition-System\cleaned_md.csv')

In [4]:
df

,Unnamed: 0,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory,Disease
0,0,23,1,17.5,102,177,161,88,0,0,2,0,1
1,1,69,1,31.1,118,256,147,92,0,0,0,1,4
2,2,61,0,31.3,114,206,193,74,1,0,2,0,1
3,3,47,0,23.9,105,162,253,68,0,0,1,0,1
4,4,47,1,28.3,148,121,280,84,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,49,1,27.1,177,183,268,59,0,0,0,0,3
9996,9996,84,1,29.2,142,215,145,77,0,1,0,1,3
9997,9997,41,1,22.8,177,265,133,71,0,0,2,1,3
9998,9998,55,1,29.0,126,241,298,57,0,0,2,1,4


In [5]:
df.drop('Unnamed: 0',axis =1,inplace =True)

In [6]:
df

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory,Disease
0,23,1,17.5,102,177,161,88,0,0,2,0,1
1,69,1,31.1,118,256,147,92,0,0,0,1,4
2,61,0,31.3,114,206,193,74,1,0,2,0,1
3,47,0,23.9,105,162,253,68,0,0,1,0,1
4,47,1,28.3,148,121,280,84,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,49,1,27.1,177,183,268,59,0,0,0,0,3
9996,84,1,29.2,142,215,145,77,0,1,0,1,3
9997,41,1,22.8,177,265,133,71,0,0,2,1,3
9998,55,1,29.0,126,241,298,57,0,0,2,1,4


In [7]:
x = df.drop('Disease', axis =1)

In [8]:
y  = df[['Disease']]

In [9]:
x

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory
0,23,1,17.5,102,177,161,88,0,0,2,0
1,69,1,31.1,118,256,147,92,0,0,0,1
2,61,0,31.3,114,206,193,74,1,0,2,0
3,47,0,23.9,105,162,253,68,0,0,1,0
4,47,1,28.3,148,121,280,84,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,49,1,27.1,177,183,268,59,0,0,0,0
9996,84,1,29.2,142,215,145,77,0,1,0,1
9997,41,1,22.8,177,265,133,71,0,0,2,1
9998,55,1,29.0,126,241,298,57,0,0,2,1


In [10]:
y

,Disease
0,1
1,4
2,1
3,1
4,1
...,...
9995,3
9996,3
9997,3
9998,4


In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state = 42,test_size = 0.2)

In [13]:
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((8000, 11), (8000, 1), (2000, 11), (2000, 1))

In [15]:
from sklearn.svm import SVC,SVR
sv = SVC()
sv.fit(x_train,y_train)

c:\Users\user\OneDrive\Desktop\Data Science\datascience\Lib\site-packages\sklearn\utils\validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


,"C C: float, default=1.0Regularization parameter. The strength of the regularization isinversely proportional to C. Must be strictly positive. The penaltyis a squared l2 penalty. For an intuitive visualization of the effectsof scaling the regularization parameter C, see:ref:`sphx_glr_auto_examples_svm_plot_svm_scale_c.py`.",1.0
,"kernel kernel: {'linear', 'poly', 'rbf', 'sigmoid', 'precomputed'} or callable, default='rbf'Specifies the kernel type to be used in the algorithm. Ifnone is given, 'rbf' will be used. If a callable is given it is used topre-compute the kernel matrix from data matrices; that matrix should bean array of shape ``(n_samples, n_samples)``. For an intuitivevisualization of different kernel types see:ref:`sphx_glr_auto_examples_svm_plot_svm_kernels.py`.",'rbf'
,"degree degree: int, default=3Degree of the polynomial kernel function ('poly').Must be non-negative. Ignored by all other kernels.",3
,"gamma gamma: {'scale', 'auto'} or float, default='scale'Kernel coefficient for 'rbf', 'poly' and 'sigmoid'.- if ``gamma='scale'`` (default) is passed then it uses 1 / (n_features * X.var()) as value of gamma,- if 'auto', uses 1 / n_features- if float, must be non-negative... versionchanged:: 0.22 The default value of ``gamma`` changed from 'auto' to 'scale'.",'scale'
,"coef0 coef0: float, default=0.0Independent term in kernel function.It is only significant in 'poly' and 'sigmoid'.",0.0
,"shrinking shrinking: bool, default=TrueWhether to use the shrinking heuristic.See the :ref:`User Guide <shrinking_svm>`.",True
,"probability probability: bool, default=FalseWhether to enable probability estimates. This must be enabled priorto calling `fit`, will slow down that method as it internally uses5-fold cross-validation, and `predict_proba` may be inconsistent with`predict`. Read more in the :ref:`User Guide <scores_probabilities>`...deprecated:: 1.9 The `probability` parameter is deprecated and will be removed in 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`.",'deprecated'
,"tol tol: float, default=1e-3Tolerance for stopping criterion.",0.001
,"cache_size cache_size: float, default=200Specify the size of the kernel cache (in MB).",200
,"class_weight class_weight: dict or 'balanced', default=NoneSet the parameter C of class i to class_weight[i]*C forSVC. If not given, all classes are supposed to haveweight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.",None
,"verbose verbose: bool, default=FalseEnable verbose output. Note that this setting takes advantage of aper-process runtime setting in libsvm that, if enabled, may not workproperly in a multithreaded context.",False


In [16]:
print(sv.score(x_train,y_train))
print(sv.score(x_test,y_test))

0.63125
0.6395


In [18]:
from sklearn.tree import DecisionTreeClassifier , DecisionTreeRegressor
dtc = DecisionTreeClassifier()
dtc.fit(x_train,y_train)

,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.",'gini'
,"splitter splitter: {""best"", ""random""}, default=""best""The strategy used to choose the split at each node. Supportedstrategies are ""best"" to choose the best split and ""random"" to choosethe best random split.",'best'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: int, float or {""sqrt"", ""log2""}, default=NoneThe number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... note:: The search for a split does not stop until at least one valid partition of the node samples is found, even if it requires to effectively inspect more than ``max_features`` features.",None
,"random_state random_state: int, RandomState instance or None, default=NoneControls the randomness of the estimator. The features are alwaysrandomly permuted at each split, even if ``splitter`` is set to``""best""``. When ``max_features < n_features``, the algorithm willselect ``max_features`` at random at each split before finding the bestsplit among them. But the best found split may vary across differentruns, even if ``max_features=n_features``. That is the case, if theimprovement of the criterion is identical for several splits and onesplit has to be selected at random. To obtain a deterministic behaviourduring fitting, ``random_state`` has to be fixed to an integer.See :term:`Glossary <random_state>` for details.",None
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow a tree with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsample

In [19]:
print(dtc.score(x_train,y_train))
print(dtc.score(x_test,y_test))

1.0
0.645


In [24]:
x_train

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory
9254,76,1,29.6,134,266,318,101,1,0,2,1
1561,35,0,29.3,96,220,300,58,0,0,1,0
1670,69,1,29.6,164,149,229,98,0,0,1,0
6087,47,1,29.0,159,250,258,109,0,1,2,0
6669,42,1,23.4,107,224,300,82,1,0,2,0
...,...,...,...,...,...,...,...,...,...,...,...
5734,61,0,30.2,175,147,167,102,0,1,1,0
5191,79,0,20.5,150,225,142,84,0,0,2,1
5390,30,1,27.6,119,101,129,110,0,0,2,0
860,82,1,30.7,108,143,231,102,1,0,1,1


In [25]:
y_train

,Disease
9254,3
1561,1
1670,1
6087,1
6669,1
...,...
5734,4
5191,1
5390,1
860,3


In [27]:
x_test

,Age,Gender,BMI,BloodPressure,GlucoseLevel,Cholesterol,HeartRate,Smoking,Alcohol,PhysicalActivity,FamilyHistory
6252,36,1,23.5,122,156,146,99,0,1,2,1
4684,52,0,23.0,147,137,273,107,0,0,0,0
1731,78,1,26.3,118,128,125,55,0,0,2,1
4742,46,1,22.6,161,211,147,59,0,0,1,0
4521,64,0,27.2,126,261,162,108,1,1,2,0
...,...,...,...,...,...,...,...,...,...,...,...
6412,23,0,25.5,114,204,220,99,0,0,1,0
8285,20,1,32.3,131,257,287,77,0,0,1,0
7853,53,0,26.8,180,240,306,94,0,0,0,0
1095,23,0,35.2,118,148,292,100,0,0,1,0


In [29]:
y_test

,Disease
6252,1
4684,1
1731,1
4742,1
4521,3
...,...
6412,1
8285,1
7853,3
1095,1


In [30]:
dtc.predict([[36,	1	,23.5	,122	,156	,146	,99	,0	,1	,2,	1]])

c:\Users\user\OneDrive\Desktop\Data Science\datascience\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])

In [31]:
dtc.predict([[64	,0	,27.2	,126	,261	,162	,108	,1	,1	,2	,0]])

c:\Users\user\OneDrive\Desktop\Data Science\datascience\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([4])

In [26]:
y_pred = dtc.predict(x_test)

In [22]:
confusion_matrix(y_test,y_pred)

array([[  14,    0,   14,   15,    3],
       [   1, 1077,    4,   94,  103],
       [  14,    8,    6,   22,    3],
       [   9,  110,   18,  120,   99],
       [   2,   90,    7,   94,   73]])

In [23]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.645